language: node_js
node_js:
  - "0.10"
before_install:
  - npm install npm@1.4 -g
  - npm install -g grunt-cli
after_success :
  - grunt app-init
  - grunt app-build
notifications:
  email:
    recipients:
      - anab.tn@gmail.com
    on_success: [always|never|change] # default: change
    on_failure: [always|never|change] # default: always